/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Toggle all': '切换全部',
    'Hard Reset': '硬复位',
    'Helium': '氦',
    'Matter': '物质',
    'Photosynthesis': '光合作用',
    'Periodic table': '元素周期表',
    'Photonic': '光子',
    'Population': '人口',
    'Population changes': '人口变化',
    'Hotkeys': '快捷键',
    'Scientific': '科学',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Synthesis': '合成',
    'Current': '当前',
    'Courier New': '等宽字体',
    'Dimensional': '尺寸',
    'Default': '默认',
    'DIMENSIONAL SHIFT': '空间移位',
    'Dimensions': '维度',
    'Electrons': '电子',
    'Enabled': '启用',
    'energy': '能源',
    'Evolutions': '进化',
    'EXTINCTION': '灭绝',
    'Export/Import': '导出/导入',
    'Fertility': '生育能力',
    'free levels': '免费等级',
    'Lithium': '锂',
    'Metabolism': '新陈代谢',
    'Notation': '符号',
    'Next': '下一个',
    'You need': '你需要',
    'You completed': '你完成了',
    'You have': '你有',
    'You have played for': '你玩了',
    'You spent': '你花费了',
    'Your matter filled': '你的物质填满了',
    'Your maximum Gravitons is': '你的最大引力是',
    'Your resource potential is infinite': '您的资源潜力是无限的',
    'Your species has a total population of': '你的物种的总数',
    'Vacuumic': '真空重置',
    'challenges': '挑战',
    'Challenges': '挑战',
    'dimensions': '维度',
    'Dimensions': '维度',
    'Automation Shop': '自动化商店',
    'Binary': '二进制',
    'Biological': '生物',
    'Infinity': '无限',
    'Information': '信息',
    'Infrared Waves': '红外波',
    'Infrared': '红外线',
    'Logarithm': '对数',
    'Mitochondria': '线粒体',
    'Mortality': '死亡率',
    'You can have': '你可以拥有',
    'Yellow': '黄色',
    'Vacuumic dimensions': '真空维度',
    'You gain': '你获得',
    'You started playing': '你开始玩',
    'You performed': '你的表现',
    'You need to get': '你需要去获得',
    'Electron Power': '电子功率',
    'Carbon': '碳',
    'Challenge': '挑战',
    'Changelog': '更新日志',
    'BREAK INFINITY': '打破无限',
    'Buy Nitrogen': '买氮',
    'Buy Oxygen': '买氧',
    'Collision Knowledge.': '碰撞知识。',
    'Decay Neutrons into an Electron': '将中子衰减成电子',
    'Decay Neutrons into a W-Boson': '将中子衰减成W玻色子',
    'Decay Neutrons into a Proton': '将中子衰减成质子',
    'Neutronic': '中子',
    'Neutronic particles': '中子粒子',
    'Neutronic particles are': '中子粒子',
    'Neutronic dimensions': '中子维度',
    'Close': '关闭',
    'Hex': '十六进制',
    'Gravitons.': '引力。',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    'Hydrogen': '氢',
    'Hotkeys now don\'t work on exporting/importing screen.': '热键现在不能在导出/导入屏幕上工作。',
    'Green Waves': '绿光波',
    'Get a Collision Point': '得到一个碰撞点',
    'Genetic Reshuffle': '基因改组',
    'Genetic Recombination': '基因重组',
    'Genetic Hardening': '基因强化',
    'Genetic Diversity': '遗传多样性',
    'Genes.': '基因。',
    'Evolutions with larger Advantage (shown in top-right corner) are implemented quicker.': '具有更大优势的进化(显示在右上角)实现得更快。',
    'Fertility rate is increased': '生育率上升',
    'Evolutions are implemented': '进化实现',
    'Eukaryotes': '真核生物',
    'Emit Infrared Waves': '发射红外波',
    'Emit Green Waves': '发射绿光波',
    'Emit X-Ray Waves': '发射X射线',
    'Emit Ultraviolet Waves': '发射紫外线',
    'Emit Red Waves': '发射红光波',
    'Emit Blue Waves': '发射蓝光波',
    'Challenges are now checked for completion before autobuyer actions.': '现在，在自动购买者操作之前，将检查挑战是否完成。',
    'Dimensions are working as if there are x^': '维度起作用当有 x^',
    'dimensions of each kind': '各种类型维度',
    'You need to break Infinity in order to complete Vacuumic challenges.': '你需要打破无限才能完成真空挑战。',
    'You need to get a certain amount of matter to complete Photonic challenges.': '你需要获得一定数量的物质来完成光子挑战。',
    'You need to get a certain amount of matter to complete Neutronic challenges.': '你需要获得一定数量的物质来完成中子挑战。',
    'While Infinity is broken, the resource limit is disabled': '当无限被打破时，资源限制被禁用',
    'Black Holes also increase resource limit (up to': '黑洞也增加了资源限制 (直到',
    'Unlock Tickspeed Upgrades': '解锁周期速度升级',
    'Now you no longer start the game in 1970.': '现在你不再从1970年开始游戏。',
    'Gain a percentage of Inertia income while online': '在线时获得一定百分比的惯性收入',
    'Display': '显示',
    'Display temperature in': '显示温度',
    'don\'t display': '不显示',
    'Shuffled tabs around a bit.': '杂乱无章的标签周围。',
    'Show upgrade IDs': '显示升级id',
    'Show full changelog (might include spoilers': '显示完整的更新日志(可能包括剧透',
    'Shift+V - switch to Vacuumic tab': 'Shift+V -切换到真空选项卡',
    'Shift+P - switch to Photonic tab': 'Shift+P -切换到光子选项卡',
    'Shift+N - switch to Neutronic tab': 'Shift+N -切换到中子选项卡',
    'Shift+G - switch to Gravitonic tab': 'Shift+G -切换到重力标签',
    'Shift+D - switch to Dimensional tab': 'Shift+D -切换到维度选项卡',
    'Shift+B - switch to Biological tab': 'Shift+B -切换到生物选项卡',
    'Shift+A - switch to Atomic tab': 'Shift+A -切换到原子选项卡',
    'Shift - hold to see upgrade IDs': '按住Shift键查看升级id',
    'Improve Photon gain formula': '改进光子增益公式',
    'Higher level Dimensions give more Shards': '更高层次的维度提供更多的碎片',
    'Green Waves are boosted a bit.': '绿波提升了一点。',

    //原样
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "Unlock autobuyer for ": "解锁自动购买者为",
    "Unlock Extinctions (on Population tab": "解锁灭绝 (在人口选项卡",
    "Highest unlocked element is": "最高解锁元素为",
    "Space Theorems": "空间定理",
    "Current: ": "当前: ",
    "Effect: ": "效果: ",
    "Version ": "版本 ",
    "Unlock Neutronic ": "解锁中子",
    "Unlock Photonic ": "解锁光子",
    "Total effect": "总效果",
    "Buy Space Theorem with 3rd": "购买空间定理通过第三",
    "Buy max": "购买最大",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    " Dimensional Dimension": " 尺寸维度",
    " Vacuumic Dimension": " 真空维度",
    " Photonic Dimension": " 光子维度",
    " Neutronic Dimension": " 中子维度",
    " Gravitonic Dimension": " 引力维度",
    " Matter Dimension": " 物质维度",
    " Matter Dimensions": " 物质维度",
    " resets": "重置",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^[Atomic] (.+)$/,
    /^[Dimensional] (.+)$/,
    /^(\d+)$/,
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^Beat Photonic Challenge (\d+) to unlock!$/, '击败光子挑战 $1 即可解锁！'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);